### PR TITLE
Implemented keyboard navigation for accessibility

### PR DESCRIPTION
**Pull request by lowegreg**
I needed to add accessibility to my site and was using the edited version of the control by @AndreasIgelCC. But noticed that it was an older version and had issues with alt image tags (another accessibility feature). I came up with the following solution, but if anyone can improve on it please let me know.

A huge shoutout to @rvera for great work by the way!

### CODE REVIEW

**Comment by lowegreg** [comment]
Hold off on merging this request.  I've been working on an accessible star rater and have come up with more intuitive keyboard navigation.

**Comment by rvera** [comment]
Will do, thanks for working on this.

**Comment by lowegreg** [comment]
Okay, I've rewritten the keyboard control functions to better match 'normal' form behaviour.  Tab to enter the control and cursor to move around within the control while enter and spacebar calls the click function.  When you leave the control either by keyboard or mouse it places a tabstop to either the selected value if one exits or the first available item.  I'm always open to improvements so if anyone has suggestions on improving either the functionality or my syntax please let me know.

@rvera one issue is I don't write coffeeScript.  Did you want to lend a hand with that section?

Cheers,
Greg

**Comment by lowegreg** [comment]
Oops, I found one error that comes up when you have multiple image-pickers next to each other.  I have also not done any testing using the font awesome implementation.  Update coming soon...

Cheers,
Greg

**Comment by lowegreg** [comment]
Oaky,

I'm done with the updates.  @rvera as I mentioned I'm not that proficient in coffee, so I've only update the js files.  If someone wants to make the required coffee script changes feel free.  I hope this is helpful to some ppl.

Cheers,
Greg

**Comment by Humni** [comment]
I'll have a go at putting it into coffee script for you

**Comment by lowegreg** [comment]
Thanks @Humni if you have any question or can improve the script pls let me know...

G

**Comment by lowegreg** [comment]
@Humni I can't stop playing with this code.  I found another bug, which is VERY small and I'm probably the only one who would ever come across it.  I will get a fix up later today, but if I'm making this small change, I thought I'd test the font awesome integration.  Does anyone have a sample index file that uses .fa images???

G

**Comment by rvera** [comment]
I don't at hand, but you can find the code for the github page here https://github.com/rvera/image-picker/tree/gh-pages which is what I usually use to test the new features. As I update the index with the new examples and test them there.

**Comment by lowegreg** [comment]
Change the tabindex element to the containing div instead of the image so it is easier to see on chrome browsers.  I also removed the tabindex if the user is using a mouse.  The addition of the focus outline was distracting for users not navigating  with a keyboard. I've tested this pretty thoroughly on chrome/firefox/safari/ie both win and mac.  I can't see any issue...  I also tried using font awesome icons in place of images and it works great.

Cheers,
Greg

@Humni Sorry mate I only made the changes to the js and css files.  If you're up for it could you update the sass and coffee files...

**Comment by Humni** [comment]
@lowegreg No worries, have updated it now. If you could please test the coffee script version that would be great

**Comment by lowegreg** [comment]
@Humni tested and everything looks good thanks.

G

**Comment by Humni** [comment]
Resolved in PR #111

**Pull request closed without merging**
