### PR TITLE
font_awesome support

### PR DESCRIPTION
**Pull request by zimmicz**
Solution for issue #42. It might be nice to be able to also display font-awesome icons with this plugin.

### CODE REVIEW

**Comment by rvera** [comment]
Hi @zimmicz, sorry for the super late reply.

When I coded this plugin I was big on CoffeeScript so the source is CS, for me to apply the patch you would need to rewrite it in CS.

**Comment by zimmicz** [comment]
Hi @rvera, 
I've alredy forgotten about this :) Wow that's bad, I have never used CS before and am quite busy right now :(

**Comment by Humni** [comment]
I have implemented this in CS, see the above pull request

**Comment by rvera** [comment]
Closing this since I merged 102

**Pull request closed without merging**
