### PR TITLE
Adding generation of custom 'class'-tags in div and img

### PR DESCRIPTION
**Pull request by poikilotherm**
I wanted to style the image picker with some classes within css.

There was no option to add custom classes to the div or img element generated by jQuery, so I added the tag 'data-img-class' to be used for that.

I hope this is of use for others, too. Would be glad if you accept this PR. Thanks!

### CODE REVIEW

**Comment by rvera** [comment]
This is a good idea, due to some conflicts I can't merge this but I added this on 0.3.0 and gave you credit for the good idea!

**Comment by kevinwheeler** [comment]
Is anyone else having issues with this not working? I am using version 0.3.0 via bower. data-img-src works fine, but data-img-class does nothing.

**Comment by rvera** [comment]
Hi Kevin, maybe the bower version is wrong?

Check the demo page http://rvera.github.io/image-picker and look at the options

screen shot 2016-10-18 at 5 33 04 pm

It produces the expected result

screen shot 2016-10-18 at 5 33 17 pm

**Comment by haria** [comment]
Hi, kevinwheeler, tried use image-picker.js instead of image-picker.min.js and it is working. I guess image-picker.min.js not updated yet.

**Comment by rvera** [comment]
uh, that's weird. Thanks @haria will take a look at that.

**Pull request closed without merging**
